### ISSUE TITLE
[Postlist] Render data using React/Redux

### ISSUE THREAD

**Issue by wakoong** [bookflex/bookflex#25]
Task: 

- [ ]  Display five best-rated posts and five random posts 
   - [ ]  bookflex-client request RESTAPI
   - [ ]  bookflex-server access database
   - [ ]  bookflex-server send responsive
   - [ ]  bookflex-client receive responsive
   - [ ]  bookflex-client mapPropstoState PostList

ETA: 2~3 hours

**Comment by breakstorm** [comment]
POST부분 랜더링 완료
